version: '2'
services:
  limber:
    build: .
    image: limber
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_URL: mongodb://db/limber
  db:
    image: mvertes/alpine-mongo
    restart: always
    expose:
      - 27017
  redis:
    image: smebberson/alpine-redis
    restart: always
    expose:
      - 6379
  chatservice:
      container_name: chatservice-container
      build: chatservice
      image: chatservice
      restart: always
      links:
        - redis
      depends_on:
        - redis
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
